name: Statoscope upload reference statistics

on:
  push:
    branches: [ master ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Reconfigure git to use HTTPS authentication
      uses: GuillaumeFalourd/SSH-to-HTTPS@v1
    - name: Setup Node.js ${{ vars.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}
    - name: Install
      run: npm ci
    - name: Build
      run: |
        npm run statoscope:build
        mv ./dist/statoscope-build-statistics.json ./statoscope-reference.json
    - uses: actions/upload-artifact@v4
      with:
        name: statoscope-reference
        path: ./statoscope-reference.json
