name: Statoscope Bundle Analytics

on:
  pull_request:
    branches:
      - '*'

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTPS authentication
        uses: GuillaumeFalourd/SSH-to-HTTPS@v1
      - name: Setup Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Install
        run: npm ci
      - name: Cache results
        uses: actions/cache@v4
        id: cache-results
        with:
          path: |
            node_modules
          key: ${{ github.sha }}
  statoscope:
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTPS authentication
        uses: GuillaumeFalourd/SSH-to-HTTPS@v1
      - name: Setup Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Restore cache
        uses: actions/cache@v4
        id: restore-cache
        with:
          path: |
            node_modules
          key: ${{ github.sha }}
      - name: Download reference statistics
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: statoscope-upload-reference-statistics.yml
          workflow_conclusion: success
          name: statoscope-reference
          path: ./
        continue-on-error: true
      - name: Build
        env:
          STATOSCOPE_STATS_TO_COMPARE: statoscope-reference.json
        run: npm run statoscope:build
      - name: Prepare statoscope input
        run: |
          mv dist/statoscope-build-statistics.json input.json
          mv statoscope-reference.json reference.json
      - name: Validate
        run: npm run statoscope:validate-diff
      - name: Upload statoscope report
        uses: actions/upload-artifact@v4
        id: upload-report
        with:
          name: Statoscope report
          path: ./dist/statoscope-report.html
          if-no-files-found: error
      - name: Query stats
        if: ${{ github.event_name == 'pull_request' }}
        run: cat .github/workflows/statoscope-comment.jora | npx --no-install @statoscope/cli query --input input.json --input reference.json > statoscope-result.json
      - name: Hide bot comments
        if: ${{ github.event_name == 'pull_request' }}
        uses: int128/hide-comment-action@v1
      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const createStatoscopeComment = require('./dev/statoscopeCreateComment');
            await createStatoscopeComment({ github, context, core, diffReportUrl: '${{ steps.upload-report.outputs.artifact-url }}' })
      - name: Cleanup
        run: rm input.json; rm reference.json
